= VideoShop - A Salespoint example project
:experimental:

image:https://travis-ci.org/st-tu-dresden/videoshop.svg?branch=master["Build Status", link="https://travis-ci.org/st-tu-dresden/videoshop"]

Purpose of this sample project is to make students familiar with basic technologies they're going to use during the Software Engineering Lab at Technical University of Dresden.

## Quickstart

NOTE: The Quickstart requires Java 8, Maven 3 and a recent Git (2.0.x preferred) to be available on your machine. If you miss any of those go through the steps described in <<prerequisites>>

[source, shell]
----
$ git clone https://github.com/st-tu-dresden/videoshop
$ cd videoshop
$ mvn clean package
$ mvn spring-boot:run
----

After that point your browser to `http://localhost:8080`.

## Prerequisites

### Java 8

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Download] the binaries, install. Make sure the console shows something like this:

[source, bash]
----
$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
----

### Maven 3.x

http://maven.apache.org/download.cgi[Download] the binaries, unzip to an arbitrary location and make sure the `bin` folder of the unzipped result is in your path:

[source, bash]
----
$ mvn --version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"
----

### Git

http://git-scm.com/download[Download] the binaries, run the installer. Verify the command line shows something like this after install:

[source, bash]
----
$ git --version
git version 2.19.1
----

## IDE Setup

### Eclipse

Grab the latest https://spring.io/tools/sts/all[STS] (Spring Tool Suite or plain Eclipse Luna should work as well), run installer or unzip and run it.

Select menu:File[Import], select menu:Maven[Existing Maven Projects], select the folder you checked the project out into and hit btn:[Finish]. This will import the project into your workspace.

In the Console view you might wanna click the btn:[Open Console] button and select Maven Console to see that Maven is downloading dependencies, sources and Javadocs.

### IntelliJ

Grab the latest https://www.jetbrains.com/idea/download/[IntelliJ IDEA IDE] (both Community Edition and Ultimate Edition will work), install it according to the instructions on their website and run it.

From the Welcome Screen, select btn:[Import Project]. Otherwise, if you've already opened another project, you'll need to select menu:File[New > Project from existing sources]. Now, navigate to the folder you checked the project out into, select the `pom.xml` file and hit btn:[Open].

In the opened wizard, additionally select the checkboxes btn:[Import Maven projects automatically], as well as the btn:[Sources] and btn:[Documentation] checkboxes next to btn:[Automically download] and hit btn:[Next]. On the next page, do not select any profile and hit btn:[Next]. Now, ensure the Maven project is selected for import and hit btn:[Next]. On the following page, ensure you've selected a 1.8 or higher JDK and hit btn:[Next]. On the final page, leave the suggested project name as is and hit btn:[Finish].

Now you have to wait a bit while IntelliJ and Maven work on importing the project, which includes downloading all required dependencies from the internet. All IDE activities are displayed in the status bar.


## Technology stack

This sample application is build on top of the following technologies:

### Spring Boot

Rapid application development framework based on Spring (see below).

- https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle[Reference documentation]
- https://spring.io/guides[Getting started guides]
- https://projects.spring.io/spring-boot[Project home]

### Spring 4

The de-facto standard Java application framework.

- https://spring.io/guides[Getting started guides]
- https://projects.spring.io/spring-framework[Project home]

### Spring Data JPA

Spring module to easily build data acess layers using JPA 2.1 (Java Persistence API).

- https://spring.io/guides?filter=jpa[Getting started guides]
- https://projects.spring.io/spring-data-jpa[Project home]

### Thymeleaf

Library to build HTML web views using natural templating.

- https://spring.io/guides/gs/serving-web-content[Getting started guide]
- https://www.thymeleaf.org/doc/usingthymeleaf.html[Tutorial]
